[project]
name = "maitbayev-github-io"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "plotly>=6.3.1",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.4.9",
]
